name: Build Images and Deploy

on:
  push:
    branches:
      - main

env:
  NEXUS_URL: ${{secrets.NEXUS_URL}}
  NEXUS_USERNAME: ${{secrets.NEXUS_USERNAME}}
  NEXUS_PASSWORD: ${{secrets.NEXUS_PASSWORD}}
  IMAGE_REPO_NAME: ${{secrets.IMAGE_REPO_NAME}}
  KUBE_CONFIG_DATA: ${{secrets.KUBE_CONFIG_DATA}}

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to Nexus Docker Registry
      run: echo "${{ env.NEXUS_PASSWORD }}" | docker login -u "${{ env.NEXUS_USERNAME }}" --password-stdin ${{ env.NEXUS_URL }}

    - name: Build Docker Image
      run: docker build -t ${{ env.NEXUS_URL }}/${{ env.IMAGE_REPO_NAME }}:latest .

    - name: Push Docker Image
      run: docker push ${{ env.NEXUS_URL }}/${{ env.IMAGE_REPO_NAME }}:latest

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Trigger Rollout
        run: |
          echo "${{ env.KUBE_CONFIG_DATA }}" > kubeconfig.yaml
          kubectl --kubeconfig=kubeconfig.yaml rollout restart deployment yuri-deployment
          rm kubeconfig.yaml
